### ISSUE TITLE
images are still in png

### ISSUE THREAD

**Issue by sbeben** [metanas/vite-plugin-webp-generator#2]
i've ran npm install and added plugin to config with extentions, same as in the doc, but the images remain in source format.
<img width="290" alt="Screenshot 2024-06-24 at 19 13 45" src="https://github.com/metanas/vite-plugin-webp-generator/assets/58523020/f7d0c43b-b097-41d2-9d11-d75da9bba350">

**Comment by metanas** [comment]
The images are not generated on build runtime, just run you project in dev mode the webp image will be generated in the same folder as png/jpeg format

**Comment by aloayzab88** [comment]
Same problem, I tried the same cofig, even using ViteWebp.default, no webp is generated on dev or build mode. What else is needed to convert the images?

**Comment by sbeben** [comment]
@metanas any thoughts on that?
i also don't have any of images generated in my assets folder

**Comment by metanas** [comment]
@sbeben @aloayzab88 
The bundle generate only the images that are use the import statement. 

For image to be generate, you need to import within the code

```ts
import logo from @/assets/path/your-img.png
```

This how the bundle can detect the existing of image and generate webp version within the same folder

**Comment by sbeben** [comment]
<img width="634" alt="Screenshot 2024-10-29 at 12 57 44" src="https://github.com/user-attachments/assets/2077616f-0cfd-4286-a4a6-b3eeea343731">

@metanas you mean like this? (:
not working unfortunately
